image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - init: poetry install
    command: python src/main.py

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - cweijan.vscode-database-client2
    - vscode-icons-team.vscode-icons
    - dracula-theme.theme-dracula
