image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - command: python src/main.py

vscode:
  extensions:
    - ms-python.python
    - cweijan.vscode-database-client2
    - rangav.vscode-thunder-client
    - vscode-icons-team.vscode-icons
    - dracula-theme.theme-dracula
